import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/navbar";
import { red } from "@mui/material/colors";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Casey",
  description: "Generated by my brains",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{backgroundColor: '#080d08', color: '#FFFFFF'}} >
      <NavBar />
      <body style={{marginTop: 65}}>{children}</body>
    </html>
  );
}
