import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/navbar";
import { red } from "@mui/material/colors";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar />
      <body style={{paddingTop: 80, background: '#020800'}} className={inter.className}>{children}</body>
    </html>
  );
}
